Use venv for checking python stuff

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -48,14 +48,14 @@ cargo clippy --tests -- -D warnings --D clippy::pedantic || error "Clippy errors
 
 cargo test || error "Test failures"
 
-which flake518 || error "flake518 not found. Install with \`python3 -m pip install flake518\` in the desired python environment."
+VENV="$root/.venv/bin"
+if ! [[ -d "$VENV" ]]; then
+    python3 -m venv .venv
+    "$VENV/pip3" install -r "$root/requirements.txt"
+fi
 
-flake518 . || error "Python flake8 formatting errors."
+"$VENV/flake518" . || error "Python flake8 formatting errors."
 
-which black || error error "black not found. Install with \`python3 -m pip install black\` in the desired python environment."
+"$VENV/black" --check --diff . || error "Python Black formatting errors. Run \`black .\` to fix."
 
-black --check --diff . || error "Python Black formatting errors. Run \`black .\` to fix."
-
-which isort || error error "isort not found. Install with \`python3 -m pip install isort\` in the desired python environment."
-
-isort --check --diff . || error "Python isort import ordering errors. Run \`isort .\` to fix."
+"$VENV/isort" --check --diff . || error "Python isort import ordering errors. Run \`isort .\` to fix."
